from snakemake.utils import min_version
min_version("6.0")
import os

configfile: "config/config.yaml"

workdir: '/mnt/sds-hd/sd22b002/projects/OCEAN_MCFA/'

rule all:
    input:
        'results/mofacell/r2_by_sample~combined_sn10xLRCluster2.csv'

module preprocessing:
    snakefile: 'rules/preprocessing.smk'
    config: config
use rule * from preprocessing as PP_*

module mofacell:
    snakefile: 'rules/mofacell.smk'
    config: config
use rule * from mofacell as MC_*
